// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: add-ons/v1/private/add-ons.proto

package addonsv1private

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddonType int32

const (
	AddonType_ADDON_TYPE_UNSPECIFIED    AddonType = 0
	AddonType_ADDON_TYPE_REMOTE_SCORING AddonType = 1
)

// Enum value maps for AddonType.
var (
	AddonType_name = map[int32]string{
		0: "ADDON_TYPE_UNSPECIFIED",
		1: "ADDON_TYPE_REMOTE_SCORING",
	}
	AddonType_value = map[string]int32{
		"ADDON_TYPE_UNSPECIFIED":    0,
		"ADDON_TYPE_REMOTE_SCORING": 1,
	}
)

func (x AddonType) Enum() *AddonType {
	p := new(AddonType)
	*p = x
	return p
}

func (x AddonType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddonType) Descriptor() protoreflect.EnumDescriptor {
	return file_add_ons_v1_private_add_ons_proto_enumTypes[0].Descriptor()
}

func (AddonType) Type() protoreflect.EnumType {
	return &file_add_ons_v1_private_add_ons_proto_enumTypes[0]
}

func (x AddonType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddonType.Descriptor instead.
func (AddonType) EnumDescriptor() ([]byte, []int) {
	return file_add_ons_v1_private_add_ons_proto_rawDescGZIP(), []int{0}
}

type EnableAddonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddonType AddonType `protobuf:"varint,1,opt,name=addon_type,json=addonType,proto3,enum=addons.v1.private.AddonType" json:"addon_type,omitempty"`
}

func (x *EnableAddonRequest) Reset() {
	*x = EnableAddonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_add_ons_v1_private_add_ons_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableAddonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableAddonRequest) ProtoMessage() {}

func (x *EnableAddonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_add_ons_v1_private_add_ons_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableAddonRequest.ProtoReflect.Descriptor instead.
func (*EnableAddonRequest) Descriptor() ([]byte, []int) {
	return file_add_ons_v1_private_add_ons_proto_rawDescGZIP(), []int{0}
}

func (x *EnableAddonRequest) GetAddonType() AddonType {
	if x != nil {
		return x.AddonType
	}
	return AddonType_ADDON_TYPE_UNSPECIFIED
}

type EnableAddonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EnableAddonResponse) Reset() {
	*x = EnableAddonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_add_ons_v1_private_add_ons_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableAddonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableAddonResponse) ProtoMessage() {}

func (x *EnableAddonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_add_ons_v1_private_add_ons_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableAddonResponse.ProtoReflect.Descriptor instead.
func (*EnableAddonResponse) Descriptor() ([]byte, []int) {
	return file_add_ons_v1_private_add_ons_proto_rawDescGZIP(), []int{1}
}

type Addon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddonType AddonType `protobuf:"varint,1,opt,name=addon_type,json=addonType,proto3,enum=addons.v1.private.AddonType" json:"addon_type,omitempty"`
	Enabled   bool      `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *Addon) Reset() {
	*x = Addon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_add_ons_v1_private_add_ons_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Addon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Addon) ProtoMessage() {}

func (x *Addon) ProtoReflect() protoreflect.Message {
	mi := &file_add_ons_v1_private_add_ons_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Addon.ProtoReflect.Descriptor instead.
func (*Addon) Descriptor() ([]byte, []int) {
	return file_add_ons_v1_private_add_ons_proto_rawDescGZIP(), []int{2}
}

func (x *Addon) GetAddonType() AddonType {
	if x != nil {
		return x.AddonType
	}
	return AddonType_ADDON_TYPE_UNSPECIFIED
}

func (x *Addon) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ListAddonsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAddonsRequest) Reset() {
	*x = ListAddonsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_add_ons_v1_private_add_ons_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAddonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddonsRequest) ProtoMessage() {}

func (x *ListAddonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_add_ons_v1_private_add_ons_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddonsRequest.ProtoReflect.Descriptor instead.
func (*ListAddonsRequest) Descriptor() ([]byte, []int) {
	return file_add_ons_v1_private_add_ons_proto_rawDescGZIP(), []int{3}
}

type ListAddonsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addons []*Addon `protobuf:"bytes,1,rep,name=addons,proto3" json:"addons,omitempty"`
}

func (x *ListAddonsResponse) Reset() {
	*x = ListAddonsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_add_ons_v1_private_add_ons_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAddonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddonsResponse) ProtoMessage() {}

func (x *ListAddonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_add_ons_v1_private_add_ons_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddonsResponse.ProtoReflect.Descriptor instead.
func (*ListAddonsResponse) Descriptor() ([]byte, []int) {
	return file_add_ons_v1_private_add_ons_proto_rawDescGZIP(), []int{4}
}

func (x *ListAddonsResponse) GetAddons() []*Addon {
	if x != nil {
		return x.Addons
	}
	return nil
}

type DisableAddonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddonType AddonType `protobuf:"varint,1,opt,name=addon_type,json=addonType,proto3,enum=addons.v1.private.AddonType" json:"addon_type,omitempty"`
}

func (x *DisableAddonRequest) Reset() {
	*x = DisableAddonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_add_ons_v1_private_add_ons_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableAddonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableAddonRequest) ProtoMessage() {}

func (x *DisableAddonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_add_ons_v1_private_add_ons_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableAddonRequest.ProtoReflect.Descriptor instead.
func (*DisableAddonRequest) Descriptor() ([]byte, []int) {
	return file_add_ons_v1_private_add_ons_proto_rawDescGZIP(), []int{5}
}

func (x *DisableAddonRequest) GetAddonType() AddonType {
	if x != nil {
		return x.AddonType
	}
	return AddonType_ADDON_TYPE_UNSPECIFIED
}

type DisableAddonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DisableAddonResponse) Reset() {
	*x = DisableAddonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_add_ons_v1_private_add_ons_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableAddonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableAddonResponse) ProtoMessage() {}

func (x *DisableAddonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_add_ons_v1_private_add_ons_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableAddonResponse.ProtoReflect.Descriptor instead.
func (*DisableAddonResponse) Descriptor() ([]byte, []int) {
	return file_add_ons_v1_private_add_ons_proto_rawDescGZIP(), []int{6}
}

var File_add_ons_v1_private_add_ons_proto protoreflect.FileDescriptor

var file_add_ons_v1_private_add_ons_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x64, 0x64, 0x2d, 0x6f, 0x6e, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2f, 0x61, 0x64, 0x64, 0x2d, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x11, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x22, 0x51, 0x0a, 0x12, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x41,
	0x64, 0x64, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0a, 0x61,
	0x64, 0x64, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1c, 0x2e, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x61,
	0x64, 0x64, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x45, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x5e, 0x0a, 0x05, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x12, 0x3b, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x6f,
	0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x61,
	0x64, 0x64, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x61, 0x64, 0x64, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22,
	0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x46, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x61, 0x64,
	0x64, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x64, 0x64,
	0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x41,
	0x64, 0x64, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x22, 0x52, 0x0a, 0x13,
	0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x16, 0x0a, 0x14, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x64, 0x64, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x46, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x44, 0x44, 0x4f, 0x4e, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x1d, 0x0a, 0x19, 0x41, 0x44, 0x44, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x52, 0x45, 0x4d, 0x4f, 0x54, 0x45, 0x5f, 0x53, 0x43, 0x4f, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x01,
	0x32, 0xb0, 0x02, 0x0a, 0x14, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x6f,
	0x6e, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x0b, 0x45, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x12, 0x25, 0x2e, 0x61, 0x64, 0x64, 0x6f, 0x6e,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x45, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x26, 0x2e, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x61, 0x62,
	0x6c, 0x65, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x12, 0x26, 0x2e, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x44, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x27, 0x2e, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x64, 0x64, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x12, 0x24, 0x2e, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x64, 0x64, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61,
	0x64, 0x64, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x59, 0x5a, 0x57, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6b, 0x65, 0x65, 0x67, 0x61, 0x6e, 0x63, 0x72, 0x61, 0x69, 0x67, 0x63, 0x72, 0x75,
	0x69, 0x63, 0x6b, 0x73, 0x68, 0x61, 0x6e, 0x6b, 0x2f, 0x76, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x2d,
	0x61, 0x70, 0x69, 0x2d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2f, 0x61, 0x64, 0x64, 0x2d,
	0x6f, 0x6e, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3b, 0x61,
	0x64, 0x64, 0x6f, 0x6e, 0x73, 0x76, 0x31, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_add_ons_v1_private_add_ons_proto_rawDescOnce sync.Once
	file_add_ons_v1_private_add_ons_proto_rawDescData = file_add_ons_v1_private_add_ons_proto_rawDesc
)

func file_add_ons_v1_private_add_ons_proto_rawDescGZIP() []byte {
	file_add_ons_v1_private_add_ons_proto_rawDescOnce.Do(func() {
		file_add_ons_v1_private_add_ons_proto_rawDescData = protoimpl.X.CompressGZIP(file_add_ons_v1_private_add_ons_proto_rawDescData)
	})
	return file_add_ons_v1_private_add_ons_proto_rawDescData
}

var file_add_ons_v1_private_add_ons_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_add_ons_v1_private_add_ons_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_add_ons_v1_private_add_ons_proto_goTypes = []any{
	(AddonType)(0),               // 0: addons.v1.private.AddonType
	(*EnableAddonRequest)(nil),   // 1: addons.v1.private.EnableAddonRequest
	(*EnableAddonResponse)(nil),  // 2: addons.v1.private.EnableAddonResponse
	(*Addon)(nil),                // 3: addons.v1.private.Addon
	(*ListAddonsRequest)(nil),    // 4: addons.v1.private.ListAddonsRequest
	(*ListAddonsResponse)(nil),   // 5: addons.v1.private.ListAddonsResponse
	(*DisableAddonRequest)(nil),  // 6: addons.v1.private.DisableAddonRequest
	(*DisableAddonResponse)(nil), // 7: addons.v1.private.DisableAddonResponse
}
var file_add_ons_v1_private_add_ons_proto_depIdxs = []int32{
	0, // 0: addons.v1.private.EnableAddonRequest.addon_type:type_name -> addons.v1.private.AddonType
	0, // 1: addons.v1.private.Addon.addon_type:type_name -> addons.v1.private.AddonType
	3, // 2: addons.v1.private.ListAddonsResponse.addons:type_name -> addons.v1.private.Addon
	0, // 3: addons.v1.private.DisableAddonRequest.addon_type:type_name -> addons.v1.private.AddonType
	1, // 4: addons.v1.private.PrivateAddonsService.EnableAddon:input_type -> addons.v1.private.EnableAddonRequest
	6, // 5: addons.v1.private.PrivateAddonsService.DisableAddon:input_type -> addons.v1.private.DisableAddonRequest
	4, // 6: addons.v1.private.PrivateAddonsService.ListAddons:input_type -> addons.v1.private.ListAddonsRequest
	2, // 7: addons.v1.private.PrivateAddonsService.EnableAddon:output_type -> addons.v1.private.EnableAddonResponse
	7, // 8: addons.v1.private.PrivateAddonsService.DisableAddon:output_type -> addons.v1.private.DisableAddonResponse
	5, // 9: addons.v1.private.PrivateAddonsService.ListAddons:output_type -> addons.v1.private.ListAddonsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_add_ons_v1_private_add_ons_proto_init() }
func file_add_ons_v1_private_add_ons_proto_init() {
	if File_add_ons_v1_private_add_ons_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_add_ons_v1_private_add_ons_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EnableAddonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_add_ons_v1_private_add_ons_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*EnableAddonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_add_ons_v1_private_add_ons_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Addon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_add_ons_v1_private_add_ons_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ListAddonsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_add_ons_v1_private_add_ons_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ListAddonsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_add_ons_v1_private_add_ons_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DisableAddonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_add_ons_v1_private_add_ons_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DisableAddonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_add_ons_v1_private_add_ons_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_add_ons_v1_private_add_ons_proto_goTypes,
		DependencyIndexes: file_add_ons_v1_private_add_ons_proto_depIdxs,
		EnumInfos:         file_add_ons_v1_private_add_ons_proto_enumTypes,
		MessageInfos:      file_add_ons_v1_private_add_ons_proto_msgTypes,
	}.Build()
	File_add_ons_v1_private_add_ons_proto = out.File
	file_add_ons_v1_private_add_ons_proto_rawDesc = nil
	file_add_ons_v1_private_add_ons_proto_goTypes = nil
	file_add_ons_v1_private_add_ons_proto_depIdxs = nil
}
