// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: draw/v1/private/draw.proto

package drawv1privateconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	private "github.com/keegancraigcruickshank/volley-api-connect/draw/v1/private"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// PrivateDrawServiceName is the fully-qualified name of the PrivateDrawService service.
	PrivateDrawServiceName = "draw.v1.private.PrivateDrawService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PrivateDrawServiceCreateDrawProcedure is the fully-qualified name of the PrivateDrawService's
	// CreateDraw RPC.
	PrivateDrawServiceCreateDrawProcedure = "/draw.v1.private.PrivateDrawService/CreateDraw"
	// PrivateDrawServiceGetDrawProcedure is the fully-qualified name of the PrivateDrawService's
	// GetDraw RPC.
	PrivateDrawServiceGetDrawProcedure = "/draw.v1.private.PrivateDrawService/GetDraw"
	// PrivateDrawServiceUpdateDrawProcedure is the fully-qualified name of the PrivateDrawService's
	// UpdateDraw RPC.
	PrivateDrawServiceUpdateDrawProcedure = "/draw.v1.private.PrivateDrawService/UpdateDraw"
	// PrivateDrawServiceDeleteDrawProcedure is the fully-qualified name of the PrivateDrawService's
	// DeleteDraw RPC.
	PrivateDrawServiceDeleteDrawProcedure = "/draw.v1.private.PrivateDrawService/DeleteDraw"
	// PrivateDrawServiceGetDrawRoundProcedure is the fully-qualified name of the PrivateDrawService's
	// GetDrawRound RPC.
	PrivateDrawServiceGetDrawRoundProcedure = "/draw.v1.private.PrivateDrawService/GetDrawRound"
)

// PrivateDrawServiceClient is a client for the draw.v1.private.PrivateDrawService service.
type PrivateDrawServiceClient interface {
	CreateDraw(context.Context, *connect_go.Request[private.CreateDrawRequest]) (*connect_go.Response[private.CreateDrawResponse], error)
	GetDraw(context.Context, *connect_go.Request[private.GetDrawRequest]) (*connect_go.Response[private.GetDrawResponse], error)
	UpdateDraw(context.Context, *connect_go.Request[private.UpdateDrawRequest]) (*connect_go.Response[private.UpdateDrawResponse], error)
	DeleteDraw(context.Context, *connect_go.Request[private.DeleteDrawRequest]) (*connect_go.Response[private.DeleteDrawResponse], error)
	GetDrawRound(context.Context, *connect_go.Request[private.GetDrawRoundRequest]) (*connect_go.Response[private.GetDrawRoundResponse], error)
}

// NewPrivateDrawServiceClient constructs a client for the draw.v1.private.PrivateDrawService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPrivateDrawServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) PrivateDrawServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &privateDrawServiceClient{
		createDraw: connect_go.NewClient[private.CreateDrawRequest, private.CreateDrawResponse](
			httpClient,
			baseURL+PrivateDrawServiceCreateDrawProcedure,
			opts...,
		),
		getDraw: connect_go.NewClient[private.GetDrawRequest, private.GetDrawResponse](
			httpClient,
			baseURL+PrivateDrawServiceGetDrawProcedure,
			opts...,
		),
		updateDraw: connect_go.NewClient[private.UpdateDrawRequest, private.UpdateDrawResponse](
			httpClient,
			baseURL+PrivateDrawServiceUpdateDrawProcedure,
			opts...,
		),
		deleteDraw: connect_go.NewClient[private.DeleteDrawRequest, private.DeleteDrawResponse](
			httpClient,
			baseURL+PrivateDrawServiceDeleteDrawProcedure,
			opts...,
		),
		getDrawRound: connect_go.NewClient[private.GetDrawRoundRequest, private.GetDrawRoundResponse](
			httpClient,
			baseURL+PrivateDrawServiceGetDrawRoundProcedure,
			opts...,
		),
	}
}

// privateDrawServiceClient implements PrivateDrawServiceClient.
type privateDrawServiceClient struct {
	createDraw   *connect_go.Client[private.CreateDrawRequest, private.CreateDrawResponse]
	getDraw      *connect_go.Client[private.GetDrawRequest, private.GetDrawResponse]
	updateDraw   *connect_go.Client[private.UpdateDrawRequest, private.UpdateDrawResponse]
	deleteDraw   *connect_go.Client[private.DeleteDrawRequest, private.DeleteDrawResponse]
	getDrawRound *connect_go.Client[private.GetDrawRoundRequest, private.GetDrawRoundResponse]
}

// CreateDraw calls draw.v1.private.PrivateDrawService.CreateDraw.
func (c *privateDrawServiceClient) CreateDraw(ctx context.Context, req *connect_go.Request[private.CreateDrawRequest]) (*connect_go.Response[private.CreateDrawResponse], error) {
	return c.createDraw.CallUnary(ctx, req)
}

// GetDraw calls draw.v1.private.PrivateDrawService.GetDraw.
func (c *privateDrawServiceClient) GetDraw(ctx context.Context, req *connect_go.Request[private.GetDrawRequest]) (*connect_go.Response[private.GetDrawResponse], error) {
	return c.getDraw.CallUnary(ctx, req)
}

// UpdateDraw calls draw.v1.private.PrivateDrawService.UpdateDraw.
func (c *privateDrawServiceClient) UpdateDraw(ctx context.Context, req *connect_go.Request[private.UpdateDrawRequest]) (*connect_go.Response[private.UpdateDrawResponse], error) {
	return c.updateDraw.CallUnary(ctx, req)
}

// DeleteDraw calls draw.v1.private.PrivateDrawService.DeleteDraw.
func (c *privateDrawServiceClient) DeleteDraw(ctx context.Context, req *connect_go.Request[private.DeleteDrawRequest]) (*connect_go.Response[private.DeleteDrawResponse], error) {
	return c.deleteDraw.CallUnary(ctx, req)
}

// GetDrawRound calls draw.v1.private.PrivateDrawService.GetDrawRound.
func (c *privateDrawServiceClient) GetDrawRound(ctx context.Context, req *connect_go.Request[private.GetDrawRoundRequest]) (*connect_go.Response[private.GetDrawRoundResponse], error) {
	return c.getDrawRound.CallUnary(ctx, req)
}

// PrivateDrawServiceHandler is an implementation of the draw.v1.private.PrivateDrawService service.
type PrivateDrawServiceHandler interface {
	CreateDraw(context.Context, *connect_go.Request[private.CreateDrawRequest]) (*connect_go.Response[private.CreateDrawResponse], error)
	GetDraw(context.Context, *connect_go.Request[private.GetDrawRequest]) (*connect_go.Response[private.GetDrawResponse], error)
	UpdateDraw(context.Context, *connect_go.Request[private.UpdateDrawRequest]) (*connect_go.Response[private.UpdateDrawResponse], error)
	DeleteDraw(context.Context, *connect_go.Request[private.DeleteDrawRequest]) (*connect_go.Response[private.DeleteDrawResponse], error)
	GetDrawRound(context.Context, *connect_go.Request[private.GetDrawRoundRequest]) (*connect_go.Response[private.GetDrawRoundResponse], error)
}

// NewPrivateDrawServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPrivateDrawServiceHandler(svc PrivateDrawServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	privateDrawServiceCreateDrawHandler := connect_go.NewUnaryHandler(
		PrivateDrawServiceCreateDrawProcedure,
		svc.CreateDraw,
		opts...,
	)
	privateDrawServiceGetDrawHandler := connect_go.NewUnaryHandler(
		PrivateDrawServiceGetDrawProcedure,
		svc.GetDraw,
		opts...,
	)
	privateDrawServiceUpdateDrawHandler := connect_go.NewUnaryHandler(
		PrivateDrawServiceUpdateDrawProcedure,
		svc.UpdateDraw,
		opts...,
	)
	privateDrawServiceDeleteDrawHandler := connect_go.NewUnaryHandler(
		PrivateDrawServiceDeleteDrawProcedure,
		svc.DeleteDraw,
		opts...,
	)
	privateDrawServiceGetDrawRoundHandler := connect_go.NewUnaryHandler(
		PrivateDrawServiceGetDrawRoundProcedure,
		svc.GetDrawRound,
		opts...,
	)
	return "/draw.v1.private.PrivateDrawService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PrivateDrawServiceCreateDrawProcedure:
			privateDrawServiceCreateDrawHandler.ServeHTTP(w, r)
		case PrivateDrawServiceGetDrawProcedure:
			privateDrawServiceGetDrawHandler.ServeHTTP(w, r)
		case PrivateDrawServiceUpdateDrawProcedure:
			privateDrawServiceUpdateDrawHandler.ServeHTTP(w, r)
		case PrivateDrawServiceDeleteDrawProcedure:
			privateDrawServiceDeleteDrawHandler.ServeHTTP(w, r)
		case PrivateDrawServiceGetDrawRoundProcedure:
			privateDrawServiceGetDrawRoundHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPrivateDrawServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPrivateDrawServiceHandler struct{}

func (UnimplementedPrivateDrawServiceHandler) CreateDraw(context.Context, *connect_go.Request[private.CreateDrawRequest]) (*connect_go.Response[private.CreateDrawResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("draw.v1.private.PrivateDrawService.CreateDraw is not implemented"))
}

func (UnimplementedPrivateDrawServiceHandler) GetDraw(context.Context, *connect_go.Request[private.GetDrawRequest]) (*connect_go.Response[private.GetDrawResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("draw.v1.private.PrivateDrawService.GetDraw is not implemented"))
}

func (UnimplementedPrivateDrawServiceHandler) UpdateDraw(context.Context, *connect_go.Request[private.UpdateDrawRequest]) (*connect_go.Response[private.UpdateDrawResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("draw.v1.private.PrivateDrawService.UpdateDraw is not implemented"))
}

func (UnimplementedPrivateDrawServiceHandler) DeleteDraw(context.Context, *connect_go.Request[private.DeleteDrawRequest]) (*connect_go.Response[private.DeleteDrawResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("draw.v1.private.PrivateDrawService.DeleteDraw is not implemented"))
}

func (UnimplementedPrivateDrawServiceHandler) GetDrawRound(context.Context, *connect_go.Request[private.GetDrawRoundRequest]) (*connect_go.Response[private.GetDrawRoundResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("draw.v1.private.PrivateDrawService.GetDrawRound is not implemented"))
}
