// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: locations/v1/private/locations.proto

package locationsv1privateconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	private "github.com/keegancraigcruickshank/volley-api-connect/locations/v1/private"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// PrivateLocationsServiceName is the fully-qualified name of the PrivateLocationsService service.
	PrivateLocationsServiceName = "locations.v1.private.PrivateLocationsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PrivateLocationsServiceAddLocationProcedure is the fully-qualified name of the
	// PrivateLocationsService's AddLocation RPC.
	PrivateLocationsServiceAddLocationProcedure = "/locations.v1.private.PrivateLocationsService/AddLocation"
	// PrivateLocationsServiceModifyLocationProcedure is the fully-qualified name of the
	// PrivateLocationsService's ModifyLocation RPC.
	PrivateLocationsServiceModifyLocationProcedure = "/locations.v1.private.PrivateLocationsService/ModifyLocation"
	// PrivateLocationsServiceListLocationsProcedure is the fully-qualified name of the
	// PrivateLocationsService's ListLocations RPC.
	PrivateLocationsServiceListLocationsProcedure = "/locations.v1.private.PrivateLocationsService/ListLocations"
	// PrivateLocationsServiceRemoveLocationsProcedure is the fully-qualified name of the
	// PrivateLocationsService's RemoveLocations RPC.
	PrivateLocationsServiceRemoveLocationsProcedure = "/locations.v1.private.PrivateLocationsService/RemoveLocations"
)

// PrivateLocationsServiceClient is a client for the locations.v1.private.PrivateLocationsService
// service.
type PrivateLocationsServiceClient interface {
	AddLocation(context.Context, *connect_go.Request[private.AddLocationRequest]) (*connect_go.Response[private.AddLocationResponse], error)
	ModifyLocation(context.Context, *connect_go.Request[private.ModifyLocationRequest]) (*connect_go.Response[private.ModifyLocationResponse], error)
	ListLocations(context.Context, *connect_go.Request[private.ListLocationsRequest]) (*connect_go.Response[private.ListLocationsResponse], error)
	RemoveLocations(context.Context, *connect_go.Request[private.RemoveLocationsRequest]) (*connect_go.Response[private.RemoveLocationsResponse], error)
}

// NewPrivateLocationsServiceClient constructs a client for the
// locations.v1.private.PrivateLocationsService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPrivateLocationsServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) PrivateLocationsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &privateLocationsServiceClient{
		addLocation: connect_go.NewClient[private.AddLocationRequest, private.AddLocationResponse](
			httpClient,
			baseURL+PrivateLocationsServiceAddLocationProcedure,
			opts...,
		),
		modifyLocation: connect_go.NewClient[private.ModifyLocationRequest, private.ModifyLocationResponse](
			httpClient,
			baseURL+PrivateLocationsServiceModifyLocationProcedure,
			opts...,
		),
		listLocations: connect_go.NewClient[private.ListLocationsRequest, private.ListLocationsResponse](
			httpClient,
			baseURL+PrivateLocationsServiceListLocationsProcedure,
			opts...,
		),
		removeLocations: connect_go.NewClient[private.RemoveLocationsRequest, private.RemoveLocationsResponse](
			httpClient,
			baseURL+PrivateLocationsServiceRemoveLocationsProcedure,
			opts...,
		),
	}
}

// privateLocationsServiceClient implements PrivateLocationsServiceClient.
type privateLocationsServiceClient struct {
	addLocation     *connect_go.Client[private.AddLocationRequest, private.AddLocationResponse]
	modifyLocation  *connect_go.Client[private.ModifyLocationRequest, private.ModifyLocationResponse]
	listLocations   *connect_go.Client[private.ListLocationsRequest, private.ListLocationsResponse]
	removeLocations *connect_go.Client[private.RemoveLocationsRequest, private.RemoveLocationsResponse]
}

// AddLocation calls locations.v1.private.PrivateLocationsService.AddLocation.
func (c *privateLocationsServiceClient) AddLocation(ctx context.Context, req *connect_go.Request[private.AddLocationRequest]) (*connect_go.Response[private.AddLocationResponse], error) {
	return c.addLocation.CallUnary(ctx, req)
}

// ModifyLocation calls locations.v1.private.PrivateLocationsService.ModifyLocation.
func (c *privateLocationsServiceClient) ModifyLocation(ctx context.Context, req *connect_go.Request[private.ModifyLocationRequest]) (*connect_go.Response[private.ModifyLocationResponse], error) {
	return c.modifyLocation.CallUnary(ctx, req)
}

// ListLocations calls locations.v1.private.PrivateLocationsService.ListLocations.
func (c *privateLocationsServiceClient) ListLocations(ctx context.Context, req *connect_go.Request[private.ListLocationsRequest]) (*connect_go.Response[private.ListLocationsResponse], error) {
	return c.listLocations.CallUnary(ctx, req)
}

// RemoveLocations calls locations.v1.private.PrivateLocationsService.RemoveLocations.
func (c *privateLocationsServiceClient) RemoveLocations(ctx context.Context, req *connect_go.Request[private.RemoveLocationsRequest]) (*connect_go.Response[private.RemoveLocationsResponse], error) {
	return c.removeLocations.CallUnary(ctx, req)
}

// PrivateLocationsServiceHandler is an implementation of the
// locations.v1.private.PrivateLocationsService service.
type PrivateLocationsServiceHandler interface {
	AddLocation(context.Context, *connect_go.Request[private.AddLocationRequest]) (*connect_go.Response[private.AddLocationResponse], error)
	ModifyLocation(context.Context, *connect_go.Request[private.ModifyLocationRequest]) (*connect_go.Response[private.ModifyLocationResponse], error)
	ListLocations(context.Context, *connect_go.Request[private.ListLocationsRequest]) (*connect_go.Response[private.ListLocationsResponse], error)
	RemoveLocations(context.Context, *connect_go.Request[private.RemoveLocationsRequest]) (*connect_go.Response[private.RemoveLocationsResponse], error)
}

// NewPrivateLocationsServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPrivateLocationsServiceHandler(svc PrivateLocationsServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle(PrivateLocationsServiceAddLocationProcedure, connect_go.NewUnaryHandler(
		PrivateLocationsServiceAddLocationProcedure,
		svc.AddLocation,
		opts...,
	))
	mux.Handle(PrivateLocationsServiceModifyLocationProcedure, connect_go.NewUnaryHandler(
		PrivateLocationsServiceModifyLocationProcedure,
		svc.ModifyLocation,
		opts...,
	))
	mux.Handle(PrivateLocationsServiceListLocationsProcedure, connect_go.NewUnaryHandler(
		PrivateLocationsServiceListLocationsProcedure,
		svc.ListLocations,
		opts...,
	))
	mux.Handle(PrivateLocationsServiceRemoveLocationsProcedure, connect_go.NewUnaryHandler(
		PrivateLocationsServiceRemoveLocationsProcedure,
		svc.RemoveLocations,
		opts...,
	))
	return "/locations.v1.private.PrivateLocationsService/", mux
}

// UnimplementedPrivateLocationsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPrivateLocationsServiceHandler struct{}

func (UnimplementedPrivateLocationsServiceHandler) AddLocation(context.Context, *connect_go.Request[private.AddLocationRequest]) (*connect_go.Response[private.AddLocationResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("locations.v1.private.PrivateLocationsService.AddLocation is not implemented"))
}

func (UnimplementedPrivateLocationsServiceHandler) ModifyLocation(context.Context, *connect_go.Request[private.ModifyLocationRequest]) (*connect_go.Response[private.ModifyLocationResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("locations.v1.private.PrivateLocationsService.ModifyLocation is not implemented"))
}

func (UnimplementedPrivateLocationsServiceHandler) ListLocations(context.Context, *connect_go.Request[private.ListLocationsRequest]) (*connect_go.Response[private.ListLocationsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("locations.v1.private.PrivateLocationsService.ListLocations is not implemented"))
}

func (UnimplementedPrivateLocationsServiceHandler) RemoveLocations(context.Context, *connect_go.Request[private.RemoveLocationsRequest]) (*connect_go.Response[private.RemoveLocationsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("locations.v1.private.PrivateLocationsService.RemoveLocations is not implemented"))
}
