// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: draw/v1/private/draw.proto

package drawsv1private

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DrawTeam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamId   string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TeamName string `protobuf:"bytes,2,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
}

func (x *DrawTeam) Reset() {
	*x = DrawTeam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_draw_v1_private_draw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrawTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawTeam) ProtoMessage() {}

func (x *DrawTeam) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_private_draw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawTeam.ProtoReflect.Descriptor instead.
func (*DrawTeam) Descriptor() ([]byte, []int) {
	return file_draw_v1_private_draw_proto_rawDescGZIP(), []int{0}
}

func (x *DrawTeam) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *DrawTeam) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

type Court struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourtId   string `protobuf:"bytes,1,opt,name=court_id,json=courtId,proto3" json:"court_id,omitempty"`
	CourtName string `protobuf:"bytes,2,opt,name=court_name,json=courtName,proto3" json:"court_name,omitempty"`
}

func (x *Court) Reset() {
	*x = Court{}
	if protoimpl.UnsafeEnabled {
		mi := &file_draw_v1_private_draw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Court) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Court) ProtoMessage() {}

func (x *Court) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_private_draw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Court.ProtoReflect.Descriptor instead.
func (*Court) Descriptor() ([]byte, []int) {
	return file_draw_v1_private_draw_proto_rawDescGZIP(), []int{1}
}

func (x *Court) GetCourtId() string {
	if x != nil {
		return x.CourtId
	}
	return ""
}

func (x *Court) GetCourtName() string {
	if x != nil {
		return x.CourtName
	}
	return ""
}

type Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamOne  *DrawTeam `protobuf:"bytes,1,opt,name=team_one,json=teamOne,proto3" json:"team_one,omitempty"`
	TeamTwo  *DrawTeam `protobuf:"bytes,2,opt,name=team_two,json=teamTwo,proto3" json:"team_two,omitempty"`
	GameId   string    `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Court    *Court    `protobuf:"bytes,4,opt,name=court,proto3" json:"court,omitempty"`
	Timeslot int32     `protobuf:"varint,5,opt,name=timeslot,proto3" json:"timeslot,omitempty"`
}

func (x *Game) Reset() {
	*x = Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_draw_v1_private_draw_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_private_draw_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_draw_v1_private_draw_proto_rawDescGZIP(), []int{2}
}

func (x *Game) GetTeamOne() *DrawTeam {
	if x != nil {
		return x.TeamOne
	}
	return nil
}

func (x *Game) GetTeamTwo() *DrawTeam {
	if x != nil {
		return x.TeamTwo
	}
	return nil
}

func (x *Game) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *Game) GetCourt() *Court {
	if x != nil {
		return x.Court
	}
	return nil
}

func (x *Game) GetTimeslot() int32 {
	if x != nil {
		return x.Timeslot
	}
	return 0
}

type WeeklyDraw struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WeekStarting int64   `protobuf:"varint,1,opt,name=week_starting,json=weekStarting,proto3" json:"week_starting,omitempty"`
	Game         []*Game `protobuf:"bytes,2,rep,name=game,proto3" json:"game,omitempty"`
}

func (x *WeeklyDraw) Reset() {
	*x = WeeklyDraw{}
	if protoimpl.UnsafeEnabled {
		mi := &file_draw_v1_private_draw_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeeklyDraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyDraw) ProtoMessage() {}

func (x *WeeklyDraw) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_private_draw_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyDraw.ProtoReflect.Descriptor instead.
func (*WeeklyDraw) Descriptor() ([]byte, []int) {
	return file_draw_v1_private_draw_proto_rawDescGZIP(), []int{3}
}

func (x *WeeklyDraw) GetWeekStarting() int64 {
	if x != nil {
		return x.WeekStarting
	}
	return 0
}

func (x *WeeklyDraw) GetGame() []*Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type DivisionDraw struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GradeId        string        `protobuf:"bytes,1,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	Day            string        `protobuf:"bytes,2,opt,name=day,proto3" json:"day,omitempty"`
	Weeks          []*WeeklyDraw `protobuf:"bytes,3,rep,name=weeks,proto3" json:"weeks,omitempty"`
	DivisionDrawId string        `protobuf:"bytes,4,opt,name=division_draw_id,json=divisionDrawId,proto3" json:"division_draw_id,omitempty"`
}

func (x *DivisionDraw) Reset() {
	*x = DivisionDraw{}
	if protoimpl.UnsafeEnabled {
		mi := &file_draw_v1_private_draw_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DivisionDraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivisionDraw) ProtoMessage() {}

func (x *DivisionDraw) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_private_draw_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivisionDraw.ProtoReflect.Descriptor instead.
func (*DivisionDraw) Descriptor() ([]byte, []int) {
	return file_draw_v1_private_draw_proto_rawDescGZIP(), []int{4}
}

func (x *DivisionDraw) GetGradeId() string {
	if x != nil {
		return x.GradeId
	}
	return ""
}

func (x *DivisionDraw) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *DivisionDraw) GetWeeks() []*WeeklyDraw {
	if x != nil {
		return x.Weeks
	}
	return nil
}

func (x *DivisionDraw) GetDivisionDrawId() string {
	if x != nil {
		return x.DivisionDrawId
	}
	return ""
}

type GeneratedDivisionDraw struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Draw []*DivisionDraw `protobuf:"bytes,3,rep,name=draw,proto3" json:"draw,omitempty"`
}

func (x *GeneratedDivisionDraw) Reset() {
	*x = GeneratedDivisionDraw{}
	if protoimpl.UnsafeEnabled {
		mi := &file_draw_v1_private_draw_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratedDivisionDraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedDivisionDraw) ProtoMessage() {}

func (x *GeneratedDivisionDraw) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_private_draw_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedDivisionDraw.ProtoReflect.Descriptor instead.
func (*GeneratedDivisionDraw) Descriptor() ([]byte, []int) {
	return file_draw_v1_private_draw_proto_rawDescGZIP(), []int{5}
}

func (x *GeneratedDivisionDraw) GetDraw() []*DivisionDraw {
	if x != nil {
		return x.Draw
	}
	return nil
}

type DrawDivision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GradeId string   `protobuf:"bytes,1,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	Day     string   `protobuf:"bytes,2,opt,name=day,proto3" json:"day,omitempty"`
	TeamIds []string `protobuf:"bytes,3,rep,name=team_ids,json=teamIds,proto3" json:"team_ids,omitempty"`
}

func (x *DrawDivision) Reset() {
	*x = DrawDivision{}
	if protoimpl.UnsafeEnabled {
		mi := &file_draw_v1_private_draw_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrawDivision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawDivision) ProtoMessage() {}

func (x *DrawDivision) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_private_draw_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawDivision.ProtoReflect.Descriptor instead.
func (*DrawDivision) Descriptor() ([]byte, []int) {
	return file_draw_v1_private_draw_proto_rawDescGZIP(), []int{6}
}

func (x *DrawDivision) GetGradeId() string {
	if x != nil {
		return x.GradeId
	}
	return ""
}

func (x *DrawDivision) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *DrawDivision) GetTeamIds() []string {
	if x != nil {
		return x.TeamIds
	}
	return nil
}

type CreateDrawRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Divisions    []*DrawDivision `protobuf:"bytes,1,rep,name=divisions,proto3" json:"divisions,omitempty"`
	Name         string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SeasonLength int32           `protobuf:"varint,3,opt,name=season_length,json=seasonLength,proto3" json:"season_length,omitempty"`
	StartDate    int64           `protobuf:"varint,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
}

func (x *CreateDrawRequest) Reset() {
	*x = CreateDrawRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_draw_v1_private_draw_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDrawRequest) ProtoMessage() {}

func (x *CreateDrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_private_draw_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDrawRequest.ProtoReflect.Descriptor instead.
func (*CreateDrawRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_private_draw_proto_rawDescGZIP(), []int{7}
}

func (x *CreateDrawRequest) GetDivisions() []*DrawDivision {
	if x != nil {
		return x.Divisions
	}
	return nil
}

func (x *CreateDrawRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDrawRequest) GetSeasonLength() int32 {
	if x != nil {
		return x.SeasonLength
	}
	return 0
}

func (x *CreateDrawRequest) GetStartDate() int64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

type CreateDrawResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Divisions    []*DrawDivision `protobuf:"bytes,1,rep,name=divisions,proto3" json:"divisions,omitempty"`
	Name         string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SeasonLength int32           `protobuf:"varint,3,opt,name=season_length,json=seasonLength,proto3" json:"season_length,omitempty"`
	StartDate    int64           `protobuf:"varint,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	Id           string          `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateDrawResponse) Reset() {
	*x = CreateDrawResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_draw_v1_private_draw_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDrawResponse) ProtoMessage() {}

func (x *CreateDrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_private_draw_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDrawResponse.ProtoReflect.Descriptor instead.
func (*CreateDrawResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_private_draw_proto_rawDescGZIP(), []int{8}
}

func (x *CreateDrawResponse) GetDivisions() []*DrawDivision {
	if x != nil {
		return x.Divisions
	}
	return nil
}

func (x *CreateDrawResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDrawResponse) GetSeasonLength() int32 {
	if x != nil {
		return x.SeasonLength
	}
	return 0
}

func (x *CreateDrawResponse) GetStartDate() int64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *CreateDrawResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_draw_v1_private_draw_proto protoreflect.FileDescriptor

var file_draw_v1_private_draw_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x64, 0x72, 0x61, 0x77, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2f, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x64, 0x72,
	0x61, 0x77, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x22, 0x40,
	0x0a, 0x08, 0x44, 0x72, 0x61, 0x77, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65,
	0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61,
	0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x41, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x72, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x6f, 0x75,
	0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75,
	0x72, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x75, 0x72, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x75, 0x72, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0xd8, 0x01, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x08,
	0x74, 0x65, 0x61, 0x6d, 0x5f, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x64, 0x72, 0x61, 0x77, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x44, 0x72, 0x61, 0x77, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x07, 0x74, 0x65, 0x61, 0x6d,
	0x4f, 0x6e, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x74, 0x77, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x72, 0x61, 0x77, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x44, 0x72, 0x61, 0x77, 0x54, 0x65, 0x61,
	0x6d, 0x52, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x54, 0x77, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d,
	0x65, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x72, 0x61, 0x77, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x74, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x74, 0x22, 0x5d,
	0x0a, 0x0a, 0x57, 0x65, 0x65, 0x6b, 0x6c, 0x79, 0x44, 0x72, 0x61, 0x77, 0x12, 0x23, 0x0a, 0x0d,
	0x77, 0x65, 0x65, 0x6b, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x77, 0x65, 0x65, 0x6b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e,
	0x67, 0x12, 0x2a, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x64, 0x72, 0x61, 0x77, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x99, 0x01,
	0x0a, 0x0c, 0x44, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x72, 0x61, 0x77, 0x12, 0x19,
	0x0a, 0x08, 0x67, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x67, 0x72, 0x61, 0x64, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x32, 0x0a, 0x05, 0x77,
	0x65, 0x65, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x72, 0x61,
	0x77, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x57, 0x65,
	0x65, 0x6b, 0x6c, 0x79, 0x44, 0x72, 0x61, 0x77, 0x52, 0x05, 0x77, 0x65, 0x65, 0x6b, 0x73, 0x12,
	0x28, 0x0a, 0x10, 0x64, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x72, 0x61, 0x77,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x69, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x44, 0x72, 0x61, 0x77, 0x49, 0x64, 0x22, 0x4b, 0x0a, 0x15, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x44, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x72,
	0x61, 0x77, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x72, 0x61, 0x77, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x64, 0x72, 0x61, 0x77, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x44, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x72, 0x61, 0x77,
	0x52, 0x04, 0x64, 0x72, 0x61, 0x77, 0x22, 0x56, 0x0a, 0x0c, 0x44, 0x72, 0x61, 0x77, 0x44, 0x69,
	0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x61, 0x64, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x61, 0x64, 0x65, 0x49,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x64, 0x61, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x73, 0x22, 0xa9,
	0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x09, 0x64, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x72, 0x61, 0x77, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x44, 0x72, 0x61, 0x77, 0x44,
	0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x22, 0xba, 0x01, 0x0a, 0x12, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3c, 0x0a, 0x09, 0x64, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x72, 0x61, 0x77, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x44, 0x72, 0x61, 0x77, 0x44, 0x69, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x5f, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x70, 0x0a, 0x13, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59,
	0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x12, 0x23, 0x2e, 0x64,
	0x72, 0x61, 0x77, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x64, 0x72, 0x61, 0x77, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x56, 0x5a, 0x54, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x65, 0x65, 0x67, 0x61, 0x6e, 0x63, 0x72,
	0x61, 0x69, 0x67, 0x63, 0x72, 0x75, 0x69, 0x63, 0x6b, 0x73, 0x68, 0x61, 0x6e, 0x6b, 0x2f, 0x76,
	0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x2f, 0x64, 0x72, 0x61, 0x77, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x3b, 0x64, 0x72, 0x61, 0x77, 0x73, 0x76, 0x31, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_draw_v1_private_draw_proto_rawDescOnce sync.Once
	file_draw_v1_private_draw_proto_rawDescData = file_draw_v1_private_draw_proto_rawDesc
)

func file_draw_v1_private_draw_proto_rawDescGZIP() []byte {
	file_draw_v1_private_draw_proto_rawDescOnce.Do(func() {
		file_draw_v1_private_draw_proto_rawDescData = protoimpl.X.CompressGZIP(file_draw_v1_private_draw_proto_rawDescData)
	})
	return file_draw_v1_private_draw_proto_rawDescData
}

var file_draw_v1_private_draw_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_draw_v1_private_draw_proto_goTypes = []interface{}{
	(*DrawTeam)(nil),              // 0: draws.v1.private.DrawTeam
	(*Court)(nil),                 // 1: draws.v1.private.Court
	(*Game)(nil),                  // 2: draws.v1.private.Game
	(*WeeklyDraw)(nil),            // 3: draws.v1.private.WeeklyDraw
	(*DivisionDraw)(nil),          // 4: draws.v1.private.DivisionDraw
	(*GeneratedDivisionDraw)(nil), // 5: draws.v1.private.GeneratedDivisionDraw
	(*DrawDivision)(nil),          // 6: draws.v1.private.DrawDivision
	(*CreateDrawRequest)(nil),     // 7: draws.v1.private.CreateDrawRequest
	(*CreateDrawResponse)(nil),    // 8: draws.v1.private.CreateDrawResponse
}
var file_draw_v1_private_draw_proto_depIdxs = []int32{
	0, // 0: draws.v1.private.Game.team_one:type_name -> draws.v1.private.DrawTeam
	0, // 1: draws.v1.private.Game.team_two:type_name -> draws.v1.private.DrawTeam
	1, // 2: draws.v1.private.Game.court:type_name -> draws.v1.private.Court
	2, // 3: draws.v1.private.WeeklyDraw.game:type_name -> draws.v1.private.Game
	3, // 4: draws.v1.private.DivisionDraw.weeks:type_name -> draws.v1.private.WeeklyDraw
	4, // 5: draws.v1.private.GeneratedDivisionDraw.draw:type_name -> draws.v1.private.DivisionDraw
	6, // 6: draws.v1.private.CreateDrawRequest.divisions:type_name -> draws.v1.private.DrawDivision
	6, // 7: draws.v1.private.CreateDrawResponse.divisions:type_name -> draws.v1.private.DrawDivision
	7, // 8: draws.v1.private.PrivateDrawsService.CreateDraw:input_type -> draws.v1.private.CreateDrawRequest
	8, // 9: draws.v1.private.PrivateDrawsService.CreateDraw:output_type -> draws.v1.private.CreateDrawResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_draw_v1_private_draw_proto_init() }
func file_draw_v1_private_draw_proto_init() {
	if File_draw_v1_private_draw_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_draw_v1_private_draw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DrawTeam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_draw_v1_private_draw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Court); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_draw_v1_private_draw_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_draw_v1_private_draw_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeeklyDraw); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_draw_v1_private_draw_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DivisionDraw); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_draw_v1_private_draw_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneratedDivisionDraw); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_draw_v1_private_draw_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DrawDivision); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_draw_v1_private_draw_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDrawRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_draw_v1_private_draw_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDrawResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_draw_v1_private_draw_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_draw_v1_private_draw_proto_goTypes,
		DependencyIndexes: file_draw_v1_private_draw_proto_depIdxs,
		MessageInfos:      file_draw_v1_private_draw_proto_msgTypes,
	}.Build()
	File_draw_v1_private_draw_proto = out.File
	file_draw_v1_private_draw_proto_rawDesc = nil
	file_draw_v1_private_draw_proto_goTypes = nil
	file_draw_v1_private_draw_proto_depIdxs = nil
}
