// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: users/v1/public/users.proto

package usersv1publicconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	public "github.com/keegancraigcruickshank/volley-api-connect/users/v1/public"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// PublicUsersServiceName is the fully-qualified name of the PublicUsersService service.
	PublicUsersServiceName = "users.v1.public.PublicUsersService"
)

// PublicUsersServiceClient is a client for the users.v1.public.PublicUsersService service.
type PublicUsersServiceClient interface {
	Login(context.Context, *connect_go.Request[public.LoginRequest]) (*connect_go.Response[public.LoginResponse], error)
	RefreshToken(context.Context, *connect_go.Request[public.RefreshTokenRequest]) (*connect_go.Response[public.RefreshTokenResponse], error)
	CreateUser(context.Context, *connect_go.Request[public.CreateUserRequest]) (*connect_go.Response[public.CreateUserResponse], error)
}

// NewPublicUsersServiceClient constructs a client for the users.v1.public.PublicUsersService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPublicUsersServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) PublicUsersServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &publicUsersServiceClient{
		login: connect_go.NewClient[public.LoginRequest, public.LoginResponse](
			httpClient,
			baseURL+"/users.v1.public.PublicUsersService/Login",
			opts...,
		),
		refreshToken: connect_go.NewClient[public.RefreshTokenRequest, public.RefreshTokenResponse](
			httpClient,
			baseURL+"/users.v1.public.PublicUsersService/RefreshToken",
			opts...,
		),
		createUser: connect_go.NewClient[public.CreateUserRequest, public.CreateUserResponse](
			httpClient,
			baseURL+"/users.v1.public.PublicUsersService/CreateUser",
			opts...,
		),
	}
}

// publicUsersServiceClient implements PublicUsersServiceClient.
type publicUsersServiceClient struct {
	login        *connect_go.Client[public.LoginRequest, public.LoginResponse]
	refreshToken *connect_go.Client[public.RefreshTokenRequest, public.RefreshTokenResponse]
	createUser   *connect_go.Client[public.CreateUserRequest, public.CreateUserResponse]
}

// Login calls users.v1.public.PublicUsersService.Login.
func (c *publicUsersServiceClient) Login(ctx context.Context, req *connect_go.Request[public.LoginRequest]) (*connect_go.Response[public.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// RefreshToken calls users.v1.public.PublicUsersService.RefreshToken.
func (c *publicUsersServiceClient) RefreshToken(ctx context.Context, req *connect_go.Request[public.RefreshTokenRequest]) (*connect_go.Response[public.RefreshTokenResponse], error) {
	return c.refreshToken.CallUnary(ctx, req)
}

// CreateUser calls users.v1.public.PublicUsersService.CreateUser.
func (c *publicUsersServiceClient) CreateUser(ctx context.Context, req *connect_go.Request[public.CreateUserRequest]) (*connect_go.Response[public.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// PublicUsersServiceHandler is an implementation of the users.v1.public.PublicUsersService service.
type PublicUsersServiceHandler interface {
	Login(context.Context, *connect_go.Request[public.LoginRequest]) (*connect_go.Response[public.LoginResponse], error)
	RefreshToken(context.Context, *connect_go.Request[public.RefreshTokenRequest]) (*connect_go.Response[public.RefreshTokenResponse], error)
	CreateUser(context.Context, *connect_go.Request[public.CreateUserRequest]) (*connect_go.Response[public.CreateUserResponse], error)
}

// NewPublicUsersServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPublicUsersServiceHandler(svc PublicUsersServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/users.v1.public.PublicUsersService/Login", connect_go.NewUnaryHandler(
		"/users.v1.public.PublicUsersService/Login",
		svc.Login,
		opts...,
	))
	mux.Handle("/users.v1.public.PublicUsersService/RefreshToken", connect_go.NewUnaryHandler(
		"/users.v1.public.PublicUsersService/RefreshToken",
		svc.RefreshToken,
		opts...,
	))
	mux.Handle("/users.v1.public.PublicUsersService/CreateUser", connect_go.NewUnaryHandler(
		"/users.v1.public.PublicUsersService/CreateUser",
		svc.CreateUser,
		opts...,
	))
	return "/users.v1.public.PublicUsersService/", mux
}

// UnimplementedPublicUsersServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPublicUsersServiceHandler struct{}

func (UnimplementedPublicUsersServiceHandler) Login(context.Context, *connect_go.Request[public.LoginRequest]) (*connect_go.Response[public.LoginResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("users.v1.public.PublicUsersService.Login is not implemented"))
}

func (UnimplementedPublicUsersServiceHandler) RefreshToken(context.Context, *connect_go.Request[public.RefreshTokenRequest]) (*connect_go.Response[public.RefreshTokenResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("users.v1.public.PublicUsersService.RefreshToken is not implemented"))
}

func (UnimplementedPublicUsersServiceHandler) CreateUser(context.Context, *connect_go.Request[public.CreateUserRequest]) (*connect_go.Response[public.CreateUserResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("users.v1.public.PublicUsersService.CreateUser is not implemented"))
}
