name: main

on: push

jobs:      
  create_release:
    name: 🆙 Increase version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Release
        uses: lgvalle/create-release-action@release/v0.4.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
