name: Create Release on Push to Main

on: push

jobs:
  release:
    name: 🆙 Update and Publish Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract version from commit message
        id: extract-version
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if [[ $commit_message =~ \[v([0-9]+\.[0-9]+\.[0-9]+)\] ]]; then
            version="${BASH_REMATCH[1]}"
            echo "version=v$version" >> $GITHUB_OUTPUT
          else
            echo "No version found in commit message. Exiting."
            exit 1
          fi

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.extract-version.outputs.version }}
          name: ${{ steps.extract-version.outputs.version }}
          body: |
            This is an automated release for version ${{ steps.extract-version.outputs.version }}
            
            Commit message: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}